### ISSUE TITLE
META-INF/library_release.kotlin_module

### ISSUE THREAD

**Issue by hansenji** [Takhion/android-extras-delegates#1]
More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'

Because you use function extension Kotlin auto creates the META-INF/<project folder name>_release.kotlin_module file.  This conflicts with every other project that uses `library`. If this file is excluded function extensions will not work. See https://blog.jetbrains.com/kotlin/2015/09/kotlin-m13-is-out/

The compileKotlin option doesn't work.  The simplest way to fix it is to rename the library folder (We have had to go through all of our libraries and rename the library directory to fix this issue).

**Comment by jeffdcamp** [comment]
I'm seeing this issue too

**Comment by Takhion** [comment]
@hansenji ah, I see, good point! I will rename it ASAP :)

**Comment by Takhion** [comment]
btw @hansenji I found [a way to avoid renaming the project](https://github.com/Takhion/android-extras-delegates/commit/7e1ac1c7fa2b25135de29e7bc6e58ec58c01a2a5#diff-0d1d9100a9b6813b8cb5c470bf313d00R14)!

**Comment by hansenji** [comment]
@Takhion That fix is great thanks. Made my projects a lot nicer.
